# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.

def findTheDifference(self, s, t):
    s = "".join(sorted(s))
    t = "".join(sorted(t))

    for i, char in enumerate(s):
        if char != t[i]:
            return t[i]

    return t[-1]